CREATE TABLE dt_trx(
    id INT NOT NULL AUTO_INCREMENT,
    trx_id INT NOT NULL,
    param_id INT NOT NULL,
    notes TEXT,
    value VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
)ENGINE= InnoDB;